name: Detect Invisible Characters in Changed Files

on:
  pull_request:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  changed_files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Changed Files
        id: changed_files
        uses: panther-labs/github-actions/changed-files@v1

  invisible_characters:
    needs: [changed_files]
    if: needs.changed_files.outputs.changed_files != ''
    name: Detect Invisible Characters in Changed Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Detect invisible characters
        uses: panther-labs/github-actions/lint-invisible-characters@v1
        with:
          changed_files: ${{ needs.changed_files.outputs.changed_files }}