name: Release and Publish to PyPI and Docker Hub

on:
  workflow_dispatch:
    inputs:
      create_release_notes:
        description: 'Auto-generate release notes'
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache: true

    - name: Install dependencies for testing
      run: |
        uv pip install --system -e ".[dev]"

    - name: Run tests
      run: |
        pytest tests/

    - name: Install dependencies for release
      run: |
        uv pip install --system toml

    - name: Get version
      id: get_version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build package
      run: |
        mkdir -p dist
        pip install build
        python -m build

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event.inputs.create_release_notes }}" == "true" ]; then
          GENERATE_NOTES="--generate-notes"
        else
          GENERATE_NOTES=""
        fi

        gh release create v$VERSION \
          --title "v$VERSION" \
          $GENERATE_NOTES \
          --draft=false \
          dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1

  publish_pypi:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Publish to PyPI
      run: |
        uv pip install --system twine
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  publish_dockerhub:
    needs: prepare_release
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          panther/mcp-panther:latest
          panther/mcp-panther:${{ needs.prepare_release.outputs.version }}
