name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ --cov=src/mcp_panther --cov-report=term --cov-report=html --cov-report=json

    - name: Create Coverage Summary
      run: |
        echo "# Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "## Python Tests" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        python -c "import json; data = json.load(open('coverage.json')); print(f'Total coverage: {data[\"totals\"][\"percent_covered\"]:.2f}%')" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Upload detailed coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
